### ISSUE TITLE
New code to publish to hex

### ISSUE THREAD

**Issue by ChiefTwoPencils** [adz/glow_auth#3]
It would be greatly appreciated if a new version with the new gleam and dependency updates could be published to hex.

**Comment by adz** [comment]
Have just done, as 0.4.1

Haven't had much time lately, but was keen to add examples using the library in the repo as docs. Would be great if you were keen to contribute anything around that.

**Comment by ChiefTwoPencils** [comment]
I will create some examples while building it out on my end.
