### ISSUE TITLE
Optional scope in client_credentials

### ISSUE THREAD

**Issue by ChiefTwoPencils** [adz/glow_auth#4]
Some auth servers (e.g., Azure Entra ID) do not fall back to a default scope and instead fail the token request when a scope is omitted. This makes users rely on the `token_request_builder` to build up the request instead of using the `client_credentials` function. It would be great to have an optional `scope` parameter or another dedicated function.

#### Possible options
In both cases, the scope will be added to the request builder's params and request according to [RFC6749 &sect;3.3][0] and [&sect;4.4.2][1].

##### 

##### Optional `scope` parameter (breaking change)

```
pub fn client_credentials(
  client: Client(body),
  token_uri: UriAppendage,
  auth_scheme: AuthScheme,
  scope: Option(Scope)
) -> Request(String) { ... }
```

##### Dedicated function with scope

```
pub fn scoped_client_credentials(
  client: Client(body),
  token_uri: UriAppendage,
  auth_scheme: AuthScheme,
  scope: Scope
) -> Request(String) { ... }
```

##### Scope Record?
```
/// Represents the scope for a token request.
pub type Scope {
  /// Respresents a scope as a list of individual strings.
  ScopeList(List(String))
  /// Represents a scope as a string of one or more space-deliminated scopes.
  /// Useful for a single scope or when the scopes have been pre-joined.
  ScopeString(String)
}
```

Perhaps, you can think of other better options. I'm happy to implement the change based on your suggestions and feedback.

[0]: https://datatracker.ietf.org/doc/html/rfc6749#section-3.3
[1]: https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2

**Comment by adz** [comment]
Thanks, looks like an oversite that I didn't have scope in there at all.

I think we could do a Scope record, and have DefaultScope as a parameterless constructor, then we can use your `Dedicated function with scope` way with `scope` as a required parameter to client_credentials function.

**Comment by ChiefTwoPencils** [comment]
Sounds good. Just to make sure I'm understanding, it would be implemented like below on the existing `client_credentials` function; is that right?

```
pub type Scope {
  ScopeList(List(String))
  ScopeString(String)
  DefaultScope
}

pub fn client_credentials(
  client: Client(body),
  token_uri: UriAppendage,
  auth_scheme: AuthScheme,
  scope: Scope,
) -> Request(String) { ... }
```

Also, where were you wanting the usage examples to go? Should they be on the main readme?

**Comment by adz** [comment]
Looks great. Let's make it easy to find, and put a top level ./examples for now.

Thanks so much for your efforts!
