### ISSUE TITLE
token_request.authorization_code Basic Authorization header is not base64 padded

### ISSUE THREAD

**Issue by trilowy** [adz/glow_auth#6]
Hello, great lib you did there!

I have a bug when I use it with Keycloak, when I create a request to get an access_token with `token_request.authorization_code`, I get a `Invalid client or Invalid client credentials`.

I noticed it lacks in header `authorization: Basic <client_id:client_secret>` some `=` characters at the end of the base64 encoded value.

**Comment by trilowy** [comment]
Hi, can you publish a new release with the fix please?

**Comment by adz** [comment]
Just release 0.5.1 with the fix

**Comment by trilowy** [comment]
Thanks!
